name: solar_kita
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+22

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  fl_chart: ^0.36.4
  expandable: ^5.0.1
  webview_flutter: ^2.0.10
  path_provider: ^2.1.3
  share: ^2.0.4
  http: ^0.13.4
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
#  flutter_html: ^2.2.1
  dio: ^5.4.3+1
#  open_file: ^3.2.1
  url_launcher: ^6.2.6
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  onesignal_flutter: ^3.2.7
  floor: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
